version: "3"

services:
  umeed:
    image: ebrahimumee/localumee:latest
    #pull_policy: always
    # networks:
    #   - umee-1
    volumes:
      - ./config:/root/.umee/config
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "7171:7171"
    command: umeed genesis init
