version: "3.9"

services:
  umeed:
    image: ebrahimumee/localumee:latest
    volumes:
      - ./umee-home:/root/.umee
    environment:
      - name=value
    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "7171:7171"