version: "3.9"

services:
  umeed:
    # image: ebrahimumee/localumee:latest
    build:
      context: .
      dockerfile: umee.Dockerfile
      args:
        - UMEE_VERSION=rafilx/umeed-cosmwasm-permissionless
    # volumes:
    #   - ./umee-home:/root/.umee:z

    # environment:
    #   - name=value
    command: umeed start

    ports:
      - "26656:26656"
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
      - "7171:7171"