name: Docker
on: [push, pull_request]

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Start containers
      timeout-minutes: 5
      run: docker-compose up --build --abort-on-container-exit
    - name: Stop containers
      if: always()
      run: docker-compose down
